In [2]:
#Importar librerias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as pltt

In [44]:
#Descargamos la data
homi_hechos = pd.read_excel('Datasets/homicidios.xlsx', sheet_name='HECHOS')
homi_victimas = pd.read_excel('Datasets/homicidios.xlsx', sheet_name='VICTIMAS')

In [45]:
#Revisamos df homicidos hecho
homi_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [46]:
#Reemplazamos los valores nulos
homi_hechos.replace(['SD','sd','Sd'], np.nan, inplace=True)

In [47]:
#Eliminamos las columnas que tienen rebundacion de infomacion y que no necesitaremos
homi_hechos = homi_hechos.drop(['HH', 'Altura', 'Cruce', 'XY (CABA)', 'PARTICIPANTES', 'Dirección Normalizada', 'Calle'], axis=1)

In [48]:
homi_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,9,-58.50877521,-34.66977709,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,NaN
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,AV. RIESTRA Y MOM,AVENIDA,7,-58.43353773,-34.64561636,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,AU DELLEPIANE Y LACARRA,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,AV. GAONA Y TERRADA,AVENIDA,11,-58.47293407,-34.61984745,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,AV. EVA PERON 4071,AVENIDA,9,-58.47066794,-34.65021673,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,PADRE CARLOS MUJICA 709,CALLE,1,-58.37976155,-34.58679619,BICICLETA,AUTO

In [49]:
#Reemplazamos los valores nulos
homi_hechos['ACUSADO'] = homi_hechos['ACUSADO'].fillna("")
homi_hechos['VICTIMA'] = homi_hechos['VICTIMA'].fillna("")

In [50]:
#Verificamos los valores nulos
null = homi_hechos[homi_hechos.isnull().any(axis=1)]
null

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,VICTIMA,ACUSADO
119,2016-0151,1,2016-11-18,2016,11,18,20:35:00,NaN,CALLE,0,.,.,PEATON,
518,2019-0103,1,2019-12-18,2019,12,18,NaN,"PAZ, GRAL. AV. Y GRIVEO",GRAL PAZ,11,-58.52169422,-34.59471640,MOTO,MOTO

In [51]:
#Eliminamos el ID 2016-0151 por estar casi vacia sin datos 
homi_hechos = homi_hechos[homi_hechos['ID'] != '2016-0151']

In [52]:
homi_hechos.loc[:, 'HORA'] = homi_hechos.loc[:, 'HORA'].fillna("")

In [53]:
null = homi_hechos[homi_hechos.isnull().any(axis=1)]
null

Empty DataFrame
Columns: [ID, N_VICTIMAS, FECHA, AAAA, MM, DD, HORA, LUGAR_DEL_HECHO, TIPO_DE_CALLE, COMUNA, pos x, pos y, VICTIMA, ACUSADO]
Index: []

In [54]:
#Observamos que en la columna Pos x y pos Y los valores nulos se muestran con "."  los reemplazamos por nan para contabilizar
homi_hechos.loc[:, 'pos x'] = homi_hechos.loc[:, 'pos x'].replace('.', np.nan)
homi_hechos.loc[:, 'pos y'] = homi_hechos.loc[:, 'pos y'].replace('.', np.nan)

In [55]:
null = homi_hechos[homi_hechos.isnull().any(axis=1)]
null

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,VICTIMA,ACUSADO
38,2016-0052,1,2016-04-20,2016,4,20,20:00:00,AUTOPISTA LUGONES PK 10000,AUTOPISTA,13,NaN,NaN,MOTO,
106,2016-0136,1,2016-10-25,2016,10,25,00:00:00,AU BUENOS AIRES - LA PLATA KM. 4,AUTOPISTA,4,NaN,NaN,MOTO,CARGAS
139,2016-0174,1,2016-12-27,2016,12,27,00:00:00,AUTOPISTA 25 DE MAYO,AUTOPISTA,0,NaN,NaN,,
176,2017-0042,1,2017-04-10,2017,4,10,09:00:00,AV. LEOPOLDO LUGONES PKM 6900,GRAL PAZ,14,NaN,NaN,MOTO,CARGAS
180,2017-0050,2,2017-04-28,2017,4,28,11:08:08,AU PERITO MORENO Y RAMAL ENLACE AU1/AU6,AUTOPISTA,9,NaN,NaN,MOTO,CARGAS
181,2017-0051,1,2017-05-01,2017,5,1,03:47:47,AU DELLEPIANE 2400,AUTOPISTA,7,NaN,NaN,AUTO,AUTO
256,2017-0140,1,2017-11-19,2017,11,19,23:22:17,AU ARTURO FRONDIZI PKM 3100,AUTOPISTA,4,NaN,NaN,MOTO,PASAJEROS
313,2018-0039,1,2018-04-21,2018,4,21,22:15:00,AUTOPISTA LUGONES KM 4.7,AUTOPISTA,14,NaN,NaN,PEATON,AUTO
546,2020-0026,1,2020-05-17,2020,5,17,06:40:00,"LUGONES, LEOPOLDO AV. KM 6,1",AUTOPISTA,14,NaN,NaN,MOTO,OBJETO FIJO
559,2020-0039,1,2020-09-01,2020,9,1,19:17:42,MURGUIONDO 2700,CALLE,9,NaN,NaN,PEATON,CARGAS
621,2021-0023,1,2021-03-01,2021,3,1,09:20:00,"AU BUENOS AIRES LA PLATA KM 4,5",AUTOPISTA,4,NaN,NaN,MOTO,CARGAS

In [56]:
#Agregamos los ID sacados de google  
#ID 2016-0052
homi_hechos.loc[homi_hechos['ID'] == '2016-0052', 'pos x'] = -34.54233281
homi_hechos.loc[homi_hechos['ID'] == '2016-0052', 'pos y'] = -58.44974319
#ID 2016-0136 
homi_hechos.loc[homi_hechos['ID'] == '2016-0136', 'pos x'] = -34.76208169
homi_hechos.loc[homi_hechos['ID'] == '2016-0136', 'pos y'] = -58.17886722
#ID 2016-0174 le agregamos una comuna
homi_hechos.loc[homi_hechos['ID'] == '2016-0174', 'pos x'] = -34.62764437
homi_hechos.loc[homi_hechos['ID'] == '2016-0174', 'pos y'] = -58.42036642
homi_hechos.loc[homi_hechos['ID'] == '2016-0174', 'COMUNA'] = 5
#ID 2017-0042 
homi_hechos.loc[homi_hechos['ID'] == '2017-0042', 'pos x'] = -34.54805588
homi_hechos.loc[homi_hechos['ID'] == '2017-0042', 'pos y'] = -58.43849925
#ID 2017-0050
homi_hechos.loc[homi_hechos['ID'] == '2017-0050', 'pos x'] = -34.64934009
homi_hechos.loc[homi_hechos['ID'] == '2017-0050', 'pos y'] = -58.46692345
#ID 2017-0051 
homi_hechos.loc[homi_hechos['ID'] == '2017-0051', 'pos x'] = -34.66907709
homi_hechos.loc[homi_hechos['ID'] == '2017-0051', 'pos y'] = -58.47557813
#ID 2017-0140 
homi_hechos.loc[homi_hechos['ID'] == '2017-0140', 'pos x'] = -34.63755652
homi_hechos.loc[homi_hechos['ID'] == '2017-0140', 'pos y'] = -58.37683371
#ID 2018-0039 
homi_hechos.loc[homi_hechos['ID'] == '2018-0039', 'pos x'] = -34.55658135
homi_hechos.loc[homi_hechos['ID'] == '2018-0039', 'pos y'] = -58.42467450
#ID 2020-0026 
homi_hechos.loc[homi_hechos['ID'] == '2020-0026', 'pos x'] = -34.54358768
homi_hechos.loc[homi_hechos['ID'] == '2020-0026', 'pos y'] = -58.44740159
#ID 2020-0039 
homi_hechos.loc[homi_hechos['ID'] == '2020-0039', 'pos x'] = -34.66250291
homi_hechos.loc[homi_hechos['ID'] == '2020-0039', 'pos y'] = -58.49298141
#ID 2021-0023 
homi_hechos.loc[homi_hechos['ID'] == '2021-0023', 'pos x'] = -34.76208169
homi_hechos.loc[homi_hechos['ID'] == '2021-0023', 'pos y'] = -58.17886722

In [57]:
null = homi_hechos[homi_hechos.isnull().any(axis=1)]
null

Empty DataFrame
Columns: [ID, N_VICTIMAS, FECHA, AAAA, MM, DD, HORA, LUGAR_DEL_HECHO, TIPO_DE_CALLE, COMUNA, pos x, pos y, VICTIMA, ACUSADO]
Index: []

In [58]:
homi_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,9,-58.50877521,-34.66977709,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,AV. RIESTRA Y MOM,AVENIDA,7,-58.43353773,-34.64561636,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,AU DELLEPIANE Y LACARRA,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,AV. GAONA Y TERRADA,AVENIDA,11,-58.47293407,-34.61984745,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,AV. EVA PERON 4071,AVENIDA,9,-58.47066794,-34.65021673,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,PADRE CARLOS MUJICA 709,CALLE,1,-58.37976155,-34.58679619,BICICLETA,AUTO

In [59]:
#Cambiamos el valor "GRAL PAZ" a "Autopista"
homi_hechos.loc[:, 'TIPO_DE_CALLE'] = homi_hechos.loc[:, 'TIPO_DE_CALLE'].replace('GRAL PAZ', 'AUTOPISTA')

In [60]:
#Verificamos que se realizo el cambio
homi_hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,pos x,pos y,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,AV GRAL PAZ Y AV DE LOS CORRALES,AUTOPISTA,9,-58.50877521,-34.66977709,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,AV. RIESTRA Y MOM,AVENIDA,7,-58.43353773,-34.64561636,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,AU DELLEPIANE Y LACARRA,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,AV. GAONA Y TERRADA,AVENIDA,11,-58.47293407,-34.61984745,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,AV. EVA PERON 4071,AVENIDA,9,-58.47066794,-34.65021673,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,PADRE CARLOS MUJICA 709,CALLE,1,-58.37976155,-34.58679619,BICICLETA,AUTO

In [63]:
#Modificamos los nombres de las columnas pos x/pos y que segun el diccionario es Longuitud y latitud
homi_hechos = homi_hechos.rename(columns={'pos x': 'LONGITUD', 'pos y': 'LATITUD'})
#Modificar los nombres de la fecha
homi_hechos = homi_hechos.rename(columns={'AAAA': 'AÑO', 'MM': 'MES', 'DD': 'DIA'})
homi_hechos

,ID,N_VICTIMAS,FECHA,AÑO,MES,DIA,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,LONGITUD,LATITUD,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,AV GRAL PAZ Y AV DE LOS CORRALES,AUTOPISTA,9,-58.50877521,-34.66977709,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,AV. RIESTRA Y MOM,AVENIDA,7,-58.43353773,-34.64561636,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,AU DELLEPIANE Y LACARRA,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,AV. GAONA Y TERRADA,AVENIDA,11,-58.47293407,-34.61984745,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,AV. EVA PERON 4071,AVENIDA,9,-58.47066794,-34.65021673,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,PADRE CARLOS MUJICA 709,CALLE,1,-58.37976155,-34.58679619,BICICLETA,AUTO

In [64]:
#Revisamos el df homicidios victimas
homi_victimas

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50,2021-12-12 00:00:00
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00

In [65]:
#Eliminamos la rebundacia de datos 
homi_victimas = homi_victimas.drop(['FECHA', 'AAAA', 'MM', 'DD','VICTIMA'], axis=1)

In [66]:
#Reemplazamos los valores nulos
homi_victimas.replace(['SD','sd','Sd'], np.nan, inplace=True)

In [67]:
null = homi_victimas[homi_victimas.isnull().any(axis=1)]
null

      ID_hecho                   ROL       SEXO  EDAD  FECHA_FALLECIMIENTO
3    2016-0004             CONDUCTOR  MASCULINO  18.0                  NaN
16   2016-0022  PASAJERO_ACOMPAÑANTE  MASCULINO  41.0                  NaN
19   2016-0027  PASAJERO_ACOMPAÑANTE  MASCULINO  34.0                  NaN
22   2016-0031             CONDUCTOR  MASCULINO  21.0                  NaN
30   2016-0041  PASAJERO_ACOMPAÑANTE  MASCULINO   NaN  2016-03-30 00:00:00
..         ...                   ...        ...   ...                  ...
579  2020-0040             CONDUCTOR  MASCULINO   NaN  2020-09-12 00:00:00
631  2021-0012                PEATON  MASCULINO   NaN  2021-01-29 00:00:00
639  2021-0020                PEATON   FEMENINO   NaN  2021-02-21 00:00:00
647  2021-0028                PEATON  MASCULINO   NaN  2021-03-29 00:00:00
698  2021-0079                PEATON  MASCULINO   NaN  2021-10-25 00:00:00

[109 rows x 5 columns]

In [68]:
#En las columna de ROL se deja en blanco los valores NaN 
homi_victimas['ROL'] = homi_victimas['ROL'].fillna('')
#En la columna SEXO Colocamos NO DEFINIDO
homi_victimas['SEXO'] = homi_victimas['SEXO'].fillna('NO DEFINIDO')
#En la columna EDAD los remplazamos por 0
homi_victimas['EDAD'] = homi_victimas['EDAD'].fillna(0)
#En la columna FECHA FALLECIMIENTO reemplazamos por NO FALLECIDO
homi_victimas['FECHA_FALLECIMIENTO'] = homi_victimas['FECHA_FALLECIMIENTO'].fillna('NO FALLECIDO')

homi_victimas

      ID_hecho                   ROL       SEXO  EDAD  FECHA_FALLECIMIENTO
0    2016-0001             CONDUCTOR  MASCULINO  19.0  2016-01-01 00:00:00
1    2016-0002             CONDUCTOR  MASCULINO  70.0  2016-01-02 00:00:00
2    2016-0003             CONDUCTOR  MASCULINO  30.0  2016-01-03 00:00:00
3    2016-0004             CONDUCTOR  MASCULINO  18.0         NO FALLECIDO
4    2016-0005             CONDUCTOR  MASCULINO  29.0  2016-02-01 00:00:00
..         ...                   ...        ...   ...                  ...
712  2021-0092                PEATON   FEMENINO  50.0  2021-12-12 00:00:00
713  2021-0093  PASAJERO_ACOMPAÑANTE   FEMENINO  18.0  2021-12-18 00:00:00
714  2021-0094  PASAJERO_ACOMPAÑANTE   FEMENINO  43.0  2021-12-20 00:00:00
715  2021-0095             CONDUCTOR  MASCULINO  27.0  2022-01-02 00:00:00
716  2021-0096             CONDUCTOR  MASCULINO  60.0  2021-12-20 00:00:00

[717 rows x 5 columns]

In [69]:
#Realizamos este cambio de nombre para poder hacer el merge
homi_victimas= homi_victimas.rename(columns={'ID_hecho': 'ID'})
homi_victimas

            ID                   ROL       SEXO  EDAD  FECHA_FALLECIMIENTO
0    2016-0001             CONDUCTOR  MASCULINO  19.0  2016-01-01 00:00:00
1    2016-0002             CONDUCTOR  MASCULINO  70.0  2016-01-02 00:00:00
2    2016-0003             CONDUCTOR  MASCULINO  30.0  2016-01-03 00:00:00
3    2016-0004             CONDUCTOR  MASCULINO  18.0         NO FALLECIDO
4    2016-0005             CONDUCTOR  MASCULINO  29.0  2016-02-01 00:00:00
..         ...                   ...        ...   ...                  ...
712  2021-0092                PEATON   FEMENINO  50.0  2021-12-12 00:00:00
713  2021-0093  PASAJERO_ACOMPAÑANTE   FEMENINO  18.0  2021-12-18 00:00:00
714  2021-0094  PASAJERO_ACOMPAÑANTE   FEMENINO  43.0  2021-12-20 00:00:00
715  2021-0095             CONDUCTOR  MASCULINO  27.0  2022-01-02 00:00:00
716  2021-0096             CONDUCTOR  MASCULINO  60.0  2021-12-20 00:00:00

[717 rows x 5 columns]

In [70]:
#Realizamos el merge 
Homicidos_df = homi_hechos.merge(homi_victimas, on='ID', how='left')
Homicidos_df

,ID,N_VICTIMAS,FECHA,AÑO,MES,DIA,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,LONGITUD,LATITUD,VICTIMA,ACUSADO,ROL,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO,CONDUCTOR,MASCULINO,19.0,2016-01-01 00:00:00
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,AV GRAL PAZ Y AV DE LOS CORRALES,AUTOPISTA,9,-58.50877521,-34.66977709,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70.0,2016-01-02 00:00:00
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO,CONDUCTOR,MASCULINO,30.0,2016-01-03 00:00:00
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,,CONDUCTOR,MASCULINO,18.0,NO FALLECIDO
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29.0,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2021-0093,1,2021-12-13,2021,12,13,17:10:00,AV. RIESTRA Y MOM,AVENIDA,7,-58.43353773,-34.64561636,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,18.0,2021-12-18 00:00:00
712,2021-0094,1,2021-12-20,2021,12,20,01:10:00,AU DELLEPIANE Y LACARRA,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,43.0,2021-12-20 00:00:00
713,2021-0095,1,2021-12-30,2021,12,30,00:43:00,AV. GAONA Y TERRADA,AVENIDA,11,-58.47293407,-34.61984745,MOTO,CARGAS,CONDUCTOR,MASCULINO,27.0,2022-01-02 00:00:00
714,2021-0096,1,2021-12-15,2021,12,15,10:30:00,AV. EVA PERON 4071,AVENIDA,9,-58.47066794,-34.65021673,AUTO,CARGAS,CONDUCTOR,MASCULINO,60.0,2021-12-20 00:00:00
715,2021-0097,1,2021-11-18,2021,11,18,06:10:00,PADRE CARLOS MUJICA 709,CALLE,1,-58.37976155,-34.58679619,BICICLETA,AUTO,CICLISTA,MASCULINO,53.0,2021-11-19 00:00:00

In [73]:
#Cambiamos el nombre de la columa rol ya que no queda claro
Homicidos_df = Homicidos_df.rename(columns={'ROL': 'ROL_VICTIMA'})

In [74]:
#Cambiamos el tipo de dato de la columna "FECHA FALLECIMIENTO"
Homicidos_df['FECHA_FALLECIMIENTO'] = pd.to_datetime(Homicidos_df['FECHA_FALLECIMIENTO'], errors='coerce')
Homicidos_df['FECHA_FALLECIMIENTO'] = Homicidos_df['FECHA_FALLECIMIENTO'].dt.strftime('%Y-%m-%d')
Homicidos_df['FECHA_FALLECIMIENTO'] = Homicidos_df['FECHA_FALLECIMIENTO'].astype('datetime64[ns]')
Homicidos_df

,ID,N_VICTIMAS,FECHA,AÑO,MES,DIA,HORA,LUGAR_DEL_HECHO,TIPO_DE_CALLE,COMUNA,LONGITUD,LATITUD,VICTIMA,ACUSADO,ROL_VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,8,-58.47533969,-34.68757022,MOTO,AUTO,CONDUCTOR,MASCULINO,19.0,2016-01-01
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,AV GRAL PAZ Y AV DE LOS CORRALES,AUTOPISTA,9,-58.50877521,-34.66977709,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70.0,2016-01-02
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,AV ENTRE RIOS 2034,AVENIDA,1,-58.39040293,-34.63189362,MOTO,AUTO,CONDUCTOR,MASCULINO,30.0,2016-01-03
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,8,-58.46503904,-34.68092974,MOTO,,CONDUCTOR,MASCULINO,18.0,NaT
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,1,-58.38718297,-34.62246630,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29.0,2016-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2021-0093,1,2021-12-13,2021,12,13,17:10:00,AV. RIESTRA Y MOM,AVENIDA,7,-58.43353773,-34.64561636,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,18.0,2021-12-18
712,2021-0094,1,2021-12-20,2021,12,20,01:10:00,AU DELLEPIANE Y LACARRA,AUTOPISTA,9,-58.46739825,-34.65117757,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,43.0,2021-12-20
713,2021-0095,1,2021-12-30,2021,12,30,00:43:00,AV. GAONA Y TERRADA,AVENIDA,11,-58.47293407,-34.61984745,MOTO,CARGAS,CONDUCTOR,MASCULINO,27.0,2022-01-02
714,2021-0096,1,2021-12-15,2021,12,15,10:30:00,AV. EVA PERON 4071,AVENIDA,9,-58.47066794,-34.65021673,AUTO,CARGAS,CONDUCTOR,MASCULINO,60.0,2021-12-20
715,2021-0097,1,2021-11-18,2021,11,18,06:10:00,PADRE CARLOS MUJICA 709,CALLE,1,-58.37976155,-34.58679619,BICICLETA,AUTO,CICLISTA,MASCULINO,53.0,2021-11-19

In [75]:
#Lo guardamos en un archivo csv para el EDA
Homicidos_df.to_csv('Datasets/Homicidios_clean.csv', index=False)